[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["hongv <skhizein0706@gmail.com>"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
repository = ""

[dependencies]
